---
title: "All models are wrong, but some are useful - George Box"
output: html_document
---

```{css, echo = FALSE}
body {
  font-family: arial;
  font-size: 13pt;
  color: black;
}
```

<style> body {text-align: justify} </style>
Hi, I'm Seunghoon, a Data Scientist at Munich Re, the world’s leading reinsurance company headquartered in Munich, Germany. Based in New York, NY, I work for Munich Engine, a cutting-edge technology platform that leverages APIs to automate underwriting decisions. My primary responsibilities include developing quarterly updates for various pricing models by  utilizing large-scale datasets of 4M+ rows and 150+ features, developing predictive modeling for bound rate, creating ETL and EDA notebooks for actuaries, and integrating external APIs to enhance data enrichment processes using Python.  

Before joining Munich Re, I spent 3.5 years as an R&D Data Analyst at a biochemical company in Windsor, Wisconsin, specializing in bovine genetics. In this role, I applied machine learning models and time series forecasting techniques to predict Y-skew measurements and sperm motility, driving data-driven improvements in reproductive biotechnology."

